### ISSUE TITLE
hello this link can not work

### ISSUE THREAD

**Issue by rouor** [fei0810/markdownhere4zotero#1]
你好，这个链接下载不了，是失效了么？麻烦更新下链接吧 谢谢

**Comment by linsui** [comment]
https://github.com/fei0810/markdownhere4zotero/raw/master/markdownhere4zotero_kaopubear_190914.xpi

**Comment by fei0810** [comment]
> 你好，这个链接下载不了，是失效了么？麻烦更新下链接吧 谢谢

之前使用的是国外的droplr，可能国内访问有些问题，已经修改为国内无限制的奶牛快传。可以在 READme 中查看。另外， @linsui 提供的GitHub下载链接也可以的
